name: native_audio
description: "A new Dart FFI package project."
version: 0.0.1

environment:
  sdk: ^3.10.8

dependencies:
  hooks: ^1.0.1
  code_assets: ^1.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.1

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  test: ^1.25.8